// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, file_names
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions android = FirebaseOptions(

      apiKey: "AIzaSyBs5ey-pyxz-SzS1OtdPBV4XsUxguJ5koA",
      appId: "1:760938335592:android:f7ac8acdea0d6214a81add",
      messagingSenderId: "760938335592", projectId: "karma-tracking"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhhFA-79OtnZHXNt9XGLGlIp1s5maIeMQ',
    appId: '1:760938335592:ios:f2d3d4f89b108dd3a81add',
    messagingSenderId: '760938335592',
    projectId: 'karma-tracking',
    iosClientId:
    '760938335592-g42rt05a5tp0tq4jsatna3887l9efb23.apps.googleusercontent.com',
    iosBundleId: 'com.antraweb.newkarma',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8_BAn0Q1ssUPUrsgOvPnH8m8MEd5gbjE',
    appId: '1:760938335592:web:d582a3977712432ca81add',
    messagingSenderId: '760938335592',
    projectId: 'karma-tracking',
    authDomain: 'karma-tracking.firebaseapp.com',
    databaseURL: 'https://karma-tracking.firebaseio.com',
    storageBucket: 'karma-tracking.firebasestorage.app',
    measurementId: 'G-7TGRXS2F3W',
  );


}
